#
# This is free software, lisence use MIT.
# 
# 
# <https://github.com/lonesafe/openwrt-packages>
#

name: Merge-upstream
on:
  push:
    paths:
      - '.github/workflows/upstream.yml'
      - '.gitignore'
      - 'diy/**'
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:
    inputs:
      ssh:
        description: 'ssh'
        required: false
        default: 'true'
  watch:
    types: started
  repository_dispatch:

jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"
    - name: Syn upstream
      run: |
        shopt -s extglob
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf `find ./* -maxdepth 0 -type d ! -name "diy"` >/dev/null 2>&1
        function git_clone() (
          git clone --depth 1 $1 $2 || true
        )
        function git_sparse_clone() (
          branch="$1" rurl="$2" localdir="$3" && shift 3
          git clone -b $branch --depth 1 --filter=blob:none --sparse $rurl $localdir
          cd $localdir
          git sparse-checkout init --cone
          git sparse-checkout set $@
          mv -n $@ ../
          cd ..
          rm -rf $localdir
          )
        function mvdir() {
        mv -n `find $1/* -maxdepth 0 -type d` ./
        rm -rf $1
        }
        (
        git_clone https://github.com/kiddin9/my-packages && mvdir my-packages
        git_clone https://github.com/kiddin9/openwrt-bypass && mvdir openwrt-bypass
        git_clone https://github.com/kiddin9/luci-app-dnsfilter
        git_clone https://github.com/kiddin9/aria2
        git_clone https://github.com/kiddin9/luci-app-baidupcs-web
        git_clone https://github.com/kiddin9/luci-theme-edge
        git_clone https://github.com/kiddin9/autoshare && mvdir autoshare
        git_clone https://github.com/kiddin9/luci-app-xlnetacc
        git_clone https://github.com/kiddin9/qBittorrent-Enhanced-Edition
        git_clone https://github.com/kiddin9/openwrt-amule-dlp && mvdir openwrt-amule-dlp
        git_clone https://github.com/kiddin9/luci-app-wizard
        git_clone https://github.com/kiddin9/openwrt-adguardhome && mvdir openwrt-adguardhome
        git_clone https://github.com/kiddin9/openwrt-cloudreve && mvdir openwrt-cloudreve
        ) &
        (
        git_clone https://github.com/xiaorouji/openwrt-passwall && mvdir openwrt-passwall
        git_clone https://github.com/fw876/helloworld && mvdir helloworld
        git_clone https://github.com/Lienol/openwrt-package liep
        git_clone https://github.com/ysc3839/openwrt-minieap
        git_clone https://github.com/rufengsuixing/luci-app-autoipsetadder
        git_clone https://github.com/NateLol/luci-app-beardropper
        git_clone https://github.com/riverscn/openwrt-iptvhelper && mvdir openwrt-iptvhelper
        git_clone https://github.com/BoringCat/luci-app-minieap
        git_clone https://github.com/rufengsuixing/luci-app-onliner
        ) &
        (
        git_clone https://github.com/zzsj0928/luci-app-pushbot
        git_clone https://github.com/shanglanxin/luci-app-homebridge
        git_clone https://github.com/jerrykuku/luci-theme-argon
        git_clone https://github.com/jerrykuku/luci-app-argon-config
        git_clone https://github.com/jerrykuku/luci-app-vssr
        git_clone https://github.com/jerrykuku/luci-app-ttnode
        git_clone https://github.com/jerrykuku/luci-app-jd-dailybonus
        git_clone https://github.com/sirpdboy/luci-app-advanced
        git_clone https://github.com/sirpdboy/luci-app-autotimeset
        git_clone https://github.com/sirpdboy/netspeedtest && mv -n netspeedtest/luci-app-netspeedtest ./ ; rm -rf netspeedtest
        ) &
        (
        git_clone https://github.com/destan19/OpenAppFilter && mvdir OpenAppFilter
        git_clone https://github.com/esirplayground/luci-app-poweroff
        git_clone https://github.com/lvqier/luci-app-dnsmasq-ipset
        git_clone https://github.com/walkingsky/luci-wifidog luci-app-wifidog
        git_clone https://github.com/peter-tank/luci-app-autorepeater
        # git_clone https://github.com/CCnut/feed-netkeeper && mvdir feed-netkeeper
        git_clone https://github.com/brvphoenix/luci-app-wrtbwmon wrtbwmon1 && mvdir wrtbwmon1
        git_clone https://github.com/brvphoenix/wrtbwmon wrtbwmon2 && mvdir wrtbwmon2
        git_clone https://github.com/LGA1150/openwrt-sysuh3c && mvdir openwrt-sysuh3c
        git_clone https://github.com/gdck/luci-app-cupsd cupsd1 && mv -n cupsd1/luci-app-cupsd cupsd1/cups/cups ./ ; rm -rf cupsd1
        git_clone https://github.com/QiuSimons/openwrt-mos && mv -n openwrt-mos/{*mosdns,v2ray-geodata} ./ ; rm -rf openwrt-mos
        ) &
        (
        git_clone https://github.com/esirplayground/LingTiGameAcc
        git_clone https://github.com/esirplayground/luci-app-LingTiGameAcc
        git_clone https://github.com/zxlhhyccc/luci-app-v2raya
        git_clone https://github.com/jerrykuku/luci-app-go-aliyundrive-webdav
        git_clone https://github.com/SSSSSimon/tencentcloud-openwrt-plugin-ddns && mv -n tencentcloud-openwrt-plugin-ddns/tencentcloud_ddns ./luci-app-tencentddns; rm -rf tencentcloud-openwrt-plugin-ddns
        git_clone https://github.com/Tencent-Cloud-Plugins/tencentcloud-openwrt-plugin-cos && mv -n tencentcloud-openwrt-plugin-cos/tencentcloud_cos ./luci-app-tencentcloud-cos; rm -rf tencentcloud-openwrt-plugin-cos
        git_clone https://github.com/doushang/luci-app-shortcutmenu luci-shortcutmenu && mv -n luci-shortcutmenu/luci-app-shortcutmenu ./ ; rm -rf luci-shortcutmenu
        git_clone https://github.com/messense/aliyundrive-webdav aliyundrive && mv -n aliyundrive/openwrt/* ./ ; rm -rf aliyundrive
        git_clone https://github.com/sbilly/netmaker-openwrt && mv -n netmaker-openwrt/netmaker ./; rm -rf netmaker-openwrt
        git_clone https://github.com/lisaac/luci-app-dockerman dockerman && mv -n dockerman/applications/* ./; rm -rf dockerman
        ) &
        (
        #git_clone https://github.com/messense/openwrt-wiretrustee && mv -n openwrt-wiretrustee/wiretrustee ./;rm -rf openwrt-wiretrustee
        git_clone https://github.com/ophub/luci-app-amlogic amlogic && mv -n amlogic/luci-app-amlogic ./;rm -rf amlogic
        git_clone https://github.com/mingxiaoyu/luci-app-cloudflarespeedtest cloudflarespeedtest && mv -n cloudflarespeedtest/applications/* ./;rm -rf cloudflarespeedtest
        git_clone https://github.com/xiaorouji/openwrt-passwall2 passwall2 && mv -n passwall2/luci-app-passwall2 ./;rm -rf passwall2
        git clone --depth 1 -b luci https://github.com/xiaorouji/openwrt-passwall passwall && mv -n passwall/luci-app-passwall ./;rm -rf passwall
        git_clone https://github.com/messense/aliyundrive-fuse aliyundrive && mv -n aliyundrive/openwrt/* ./;rm -rf aliyundrive
        git_clone https://github.com/linkease/nas-packages && mv -n nas-packages/{network/services/*,multimedia/*} ./; rm -rf nas-packages
        git_clone https://github.com/linkease/nas-packages-luci && mv -n nas-packages-luci/luci/* ./; rm -rf nas-packages-luci
        git_clone https://github.com/linkease/istore && mv -n istore/luci/* ./; rm -rf istore
        git_clone https://github.com/linkease/openwrt-app-actions
        git_clone https://github.com/AlexZhuo/luci-app-bandwidthd
        ) &
        (
        git_clone https://github.com/fullcone-nat-nftables/nft-fullcone
        git_clone https://github.com/KyleRicardo/MentoHUST-OpenWrt-ipk
        git_clone https://github.com/frainzy1477/luci-app-clash
        git_clone https://github.com/yichya/openwrt-cloudflared
        git_clone https://github.com/peter-tank/luci-app-fullconenat
        git_clone https://github.com/sbwml/openwrt-alist && mvdir openwrt-alist
        git_clone https://github.com/gSpotx2f/luci-app-log
        git_clone https://github.com/KFERMercer/luci-app-tcpdump
        git_clone https://github.com/ykxVK8yL5L/pikpak-webdav pikpak && mv -n pikpak/openwrt/* ./;rm -rf pikpak
        git_clone https://github.com/jjm2473/openwrt-apps && rm -rf openwrt-apps/{luci-app-cpufreq,luci-app-ota,luci-alias.mk} && sed -i "s/luci-alias.mk/..\/luci.mk/" openwrt-apps/*/Makefile && mvdir openwrt-apps
        ) &
        (
        git_clone https://github.com/tty228/luci-app-serverchan
        git_clone https://github.com/4IceG/luci-app-sms-tool smstool && mvdir smstool
        git_clone https://github.com/4IceG/luci-app-modemband modemb  && mv -n modemb/* ./;rm -rf modemb
        git_clone https://github.com/ZeaKyX/speedtest-web
        git_clone https://github.com/ZeaKyX/luci-app-speedtest-web
        git_clone https://github.com/Zxilly/UA2F
        git_clone https://github.com/koshev-msk/luci-app-mmconfig
        git_clone https://github.com/koshev-msk/xmm-modem
        git_clone https://github.com/jhonathanc/ps3netsrv-openwrt && mv -n ps3netsrv-openwrt/* ./;rm -rf ps3netsrv-openwrt
        git_clone https://github.com/koshev-msk/modemfeed && mv -n modemfeed/*/*/* ./ && rm -rf modemfeed
        ) &
        (
        git_clone https://github.com/honwen/luci-app-aliddns
        git_clone https://github.com/peter-tank/luci-app-dnscrypt-proxy2
        git_clone https://github.com/NateLol/luci-app-oled
        git_clone https://github.com/4IceG/luci-app-3ginfo op3ginfo  && mv -n op3ginfo/{3ginfo,luci-app-3ginfo} ./;rm -rf op3ginfo
        git_clone https://github.com/sundaqiang/openwrt-packages && mv -n openwrt-packages/luci-* ./; rm -rf openwrt-packages
        git_clone https://github.com/vernesong/OpenClash && mv -n OpenClash/luci-app-openclash ./; rm -rf OpenClash
        ) &
        (
        svn export https://github.com/Ysurac/openmptcprouter-feeds/trunk/luci-app-iperf
        svn export https://github.com/QiuSimons/OpenWrt-Add/trunk/luci-app-irqbalance
        svn export https://github.com/sirpdboy/sirpdboy-package/trunk/luci-app-control-speedlimit
        ) &
        (
        git_sparse_clone master "https://github.com/coolsnowwolf/packages" "leanpkg" net/miniupnpd net/mwan3 multimedia/UnblockNeteaseMusic-Go \
        multimedia/UnblockNeteaseMusic net/amule net/baidupcs-web net/frp multimedia/gmediarender net/go-aliyundrive-webdav \
        net/qBittorrent-static net/qBittorrent net/transmission libs/qtbase libs/qttools libs/rblibtorrent \
        net/uugamebooster net/verysync net/vlmcsd net/dnsforwarder net/nps net/tcpping net/redsocks2 net/netatalk sound/forked-daapd
        ) &
        (
        git_sparse_clone master "https://github.com/immortalwrt/packages" "immpkgs" net/mwol \
        net/sub-web net/dnsproxy net/haproxy net/v2raya net/cdnspeedtest \
        net/subconverter net/ngrokc net/oscam net/njitclient net/scutclient net/gost net/gowebdav \
        admin/bpytop libs/jpcre2 libs/wxbase libs/rapidjson libs/libcron libs/quickjspp libs/toml11 \
        utils/cpulimit utils/filebrowser net/udp2raw
        git_sparse_clone master "https://github.com/xiaoqingfengATGH/feeds-xiaoqingfeng" "xiaoqingfeng" homeredirect luci-app-homeredirect
        ) &
        (
        git_sparse_clone develop "https://github.com/Ysurac/openmptcprouter-feeds" "openmptcp" luci-app-snmpd \
        luci-app-packet-capture luci-app-mail msmtp
        git_sparse_clone master "https://github.com/immortalwrt/immortalwrt" "immortal" package/kernel/rtl88x2bu \
        package/kernel/r8168 package/emortal/autocore  package/emortal/automount package/network/utils/fullconenat \
        package/network/utils/nftables package/libs/libnftnl package/firmware/wireless-regdb
        ) &
        git_sparse_clone master "https://github.com/coolsnowwolf/luci" "leluci" applications libs/luci-lib-fs
        mv -f applications luciapp
        rm -rf luciapp/{luci-app-qbittorrent,luci-app-cpufreq}
        git_sparse_clone master "https://github.com/immortalwrt/luci" "immluci" applications protocols/luci-proto-minieap
        mv -n applications/* luciapp/; rm -rf applications
        for ipk in $(ls -d luciapp/!(luci-app-rclone|luci-app-mwan3|luci-app-transmission)/); do
        	if [[ $(ls $ipk/po | wc -l) -gt 3 ]]; then
            rm -rf $ipk
        	fi
        done
        git_sparse_clone master "https://github.com/coolsnowwolf/lede" "leanlede" package/lean package/network/services/shellsync package/network/config/netifd
    - name: Delete duplicated packages
      run: |
        shopt -s extglob
        mv -n luciapp/!(luci-app-noddos|luci-app-cshark|luci-app-dnscrypt-proxy|luci-app-https-dns-proxy) ./ ; rm -Rf luciapp
        mv -n lean/* ./ ; rm -Rf lean
        mv -n liep/* ./ ; rm -Rf liep
        mv -n openwrt-app-actions/applications/* ./;rm -rf openwrt-app-actions
        cp -rf diy/.packages/* ./ || true
    - name: SSH connection to Actions
      uses: kiddin9/debugger-action@master
      if: github.event.inputs.ssh == 'true'
    - name: Apply patches
      run: |
        find "diy/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 -E --forward --no-backup-if-mismatch" || (curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=âŒ è½¯ä»¶åŒ…æ›´æ–°å¤±è´¥ ğŸ˜‚ https://github.com/lonesafe/openwrt_packages/actions" "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage";exit 1)

    - name: Modify
      run: |
        shopt -s extglob
        set +e
        sed -i \
        -e "s/\(network\..*\)\.ifname/\1.device/g" \
        `find \( -path "*/root/*" -o -path "*/files/*" -o -path "*/luasrc/*" \) ! -path "./base-files/*" ! -path "./dnsmasq/*" ! -path "./luci-base/*" ! -path "./ppp/*" -type f` &
        (
        bash diy/create_acl_for_luci.sh -a >/dev/null 2>&1 || true
        bash diy/convert_translation.sh -a >/dev/null 2>&1 || true
        
        #sed -i 's?"http://" + window.location.hostname?window.location.protocol + "//" + window.location.hostname?g' `find luci-app*/luasrc/view/ -maxdepth 2 -name "*.htm"`
        sed -i "/minisign:minisign/d" luci-app-dnscrypt-proxy2/Makefile
        sed -i 's/+libstdcpp/+libstdcpp +zlib/' ngrokc/Makefile
        sed -i 's/+dockerd/+dockerd +cgroupfs-mount/' luci-app-docker*/Makefile
        sed -i '$i /etc/init.d/dockerd restart &' luci-app-docker*/root/etc/uci-defaults/*
        sed -i 's/+rclone\( \|$\)/+rclone +fuse-utils\1/g' luci-app-rclone/Makefile
        sed -i 's/+libcap /+libcap +libcap-bin /' luci-app-openclash/Makefile
        sed -i 's/\(+luci-compat\)/\1 +luci-theme-argon/' luci-app-argon-config/Makefile
        sed -i 's/+vsftpd$/+vsftpd-alt/' luci-app-vsftpd/Makefile
        sed -i 's/ +uhttpd-mod-ubus//' luci-app-packet-capture/Makefile
        sed -i '/boot()/,+2d' ddns-scripts/files/etc/init.d/ddns
        sed -i 's?admin/status/channel_analysis??' luci-mod-status/root/usr/share/luci/menu.d/luci-mod-status.json
        sed -i "s/PKG_VERSION:=2/PKG_VERSION:=3/" mwan3/Makefile
        sed -i "s/default n/default y/" dockerd/Config.in
        sed -i "/+uhttpd/d" ariang/Makefile
        sed -i "s/PKG_VERSION:=2.0/PKG_VERSION:=3.0/" miniupnpd/Makefile
        cp -f autocore/files/generic/10_system.js luci-mod-status/htdocs/luci-static/resources/view/status/include/10_system.js
        sed -i '$a cgi-timeout = 300' uwsgi/files-luci-support/luci-webui.ini
        sed -i '$a cgi-timeout = 90' uwsgi/files-luci-support/luci-cgi_io.ini
        sed -i '/limit-as/c\limit-as = 5000' uwsgi/files-luci-support/luci-webui.ini
        sed -i 's/procd_set_param stderr 1/procd_set_param stderr 0/' uwsgi/files/uwsgi.init
        sed -i 's/	ip.neighbors/	luci.ip.neighbors/' luci-app-wifidog/luasrc/model/cbi/wifidog/wifidog_cfg.lua
        sed -i 's/ if aarch64||arm||i386||x86_64//' luci-app-ssr-plus/Makefile
        sed -i 's/PKG_SOURCE_DATE:=2021/PKG_SOURCE_DATE:=2023/' netifd/Makefile
        sed -i 's/PKG_SOURCE_DATE:=2/PKG_SOURCE_DATE:=3/' transmission-web-control/Makefile
        
        sed -i \
          -e 's?include \.\./\.\./\(lang\|devel\)?include $(TOPDIR)/feeds/packages/\1?' \
          -e "s/\(PKG_HASH\|PKG_MD5SUM\|PKG_MIRROR_HASH\).*/\1:=skip/" \
          -e 's?\.\./\.\./luci.mk?$(TOPDIR)/feeds/luci/luci.mk?' \
          -e 's/ca-certificates/ca-bundle/' \
          -e 's/php7/php8/g' \
          */Makefile
        ) &
        
        rm -rf base-files
        
    - name: Apply
      run: |
        Emoji=("ğŸ‰" "ğŸ¤" "âœ¨" "ğŸ" "ğŸˆ" "ğŸ„" "ğŸ¨" "ğŸ’‹" "ğŸ“" "ğŸ•" "ğŸ‰" "ğŸ’" "ğŸŒ´" "ğŸš€" "ğŸ›¸" "ğŸ—½" "â›…" "ğŸŒˆ" "ğŸ”¥" "â›„" "ğŸ¶" "ğŸ…" "ğŸ¦„" "ğŸ¤")
        rm -Rf */.git
        git reset --soft HEAD^
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 3
